import { existsSync, mkdirSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { spawn } from "node:child_process";

const root = process.cwd();
const year = Number(process.env.ADI_YEAR || 2022);
const outputPath = process.env.ADI_SQL_OUTPUT || join(root, "supabase", "adi_context_seed.sql");

const zips = await collectZips();
if (zips.length === 0) {
  console.error("No ZIP codes found. Pass ZIPs as arguments or add resources first.");
  process.exit(1);
}

console.log(`Generating ADI SQL for ${zips.length} ZIP code(s): ${zips.join(", ")}`);

const rows = [];
const failures = [];
for (const zip of zips) {
  const result = await getSociomeAdi(zip, year);
  if (result.ok) {
    rows.push(result);
    console.log(`OK ${zip}: ADI ${result.adi ?? "null"}`);
  } else {
    failures.push({ zip, error: result.error || "Unknown error" });
    console.warn(`Skip ${zip}: ${result.error || "Unknown error"}`);
  }
}

mkdirSync(join(root, "supabase"), { recursive: true });
await writeFile(outputPath, buildSql(rows, failures), "utf8");
console.log(`Wrote ${outputPath}`);
if (failures.length > 0) {
  console.warn(`${failures.length} ZIP code(s) failed; see comments in the SQL file.`);
}

async function collectZips() {
  const args = process.argv.slice(2);
  const fileArgs = args.flatMap((arg, index) => {
    if (arg === "--file" || arg === "-f") return args[index + 1] ? [args[index + 1]] : [];
    if (arg.startsWith("--file=")) return [arg.slice("--file=".length)];
    return [];
  });
  const fromFiles = (await Promise.all(fileArgs.map(readZipFile))).flat();
  const fromArgs = args
    .filter((arg, index) => {
      if (arg === "--file" || arg === "-f") return false;
      if (args[index - 1] === "--file" || args[index - 1] === "-f") return false;
      return !arg.startsWith("--file=");
    })
    .flatMap(extractZips);
  const trusted = await readJson("data/trusted-resources.json");
  const fromTrusted = trusted.flatMap((resource) => resource.zipCodes || []).flatMap(extractZips);
  const fromSqlite = await readSqliteZips();
  return [...new Set([...fromArgs, ...fromFiles, ...fromTrusted, ...fromSqlite])].sort();
}

function extractZips(value) {
  return [...String(value || "").matchAll(/\b\d{5}\b/g)].map((match) => match[0]);
}

async function readJson(path) {
  return JSON.parse(await readFile(join(root, path), "utf8"));
}

async function readZipFile(path) {
  const body = await readFile(join(root, path), "utf8");
  return extractZips(body);
}

async function readSqliteZips() {
  const dbPath = join(root, "data", "resources.sqlite");
  if (!existsSync(dbPath)) return [];
  try {
    const { DatabaseSync } = await import("node:sqlite");
    const db = new DatabaseSync(dbPath);
    const rows = db.prepare("SELECT DISTINCT zip FROM place_cache WHERE zip IS NOT NULL").all();
    db.close();
    return rows.flatMap((row) => extractZips(row.zip));
  } catch {
    return [];
  }
}

function getSociomeAdi(zip, year) {
  return new Promise((resolveResult) => {
    const child = spawn("Rscript", [join(root, "scripts", "adi_sociome.R"), zip, String(year)], {
      env: process.env
    });
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (error) => {
      resolveResult({ ok: false, error: error.message });
    });
    child.on("close", () => {
      const lastLine = stdout.trim().split("\n").filter(Boolean).at(-1);
      try {
        resolveResult(JSON.parse(lastLine || "{}"));
      } catch {
        resolveResult({ ok: false, error: stderr || "Unable to parse R output." });
      }
    });
  });
}

function buildSql(rows, failures) {
  const lines = [
    "-- Generated by npm run adi:sql.",
    "-- Run this in Supabase SQL Editor after supabase/schema.sql.",
    "",
    "insert into public.adi_context (",
    "  zip,",
    "  geography,",
    "  reference_area,",
    "  year,",
    "  adi,",
    "  financial_strength,",
    "  economic_hardship_and_inequality,",
    "  educational_attainment,",
    "  source",
    ") values"
  ];

  if (rows.length === 0) {
    lines.push("-- No successful ADI rows were generated.");
  } else {
    lines.push(rows.map(sqlTuple).join(",\n"));
    lines.push("on conflict (zip) do update set");
    lines.push("  geography = excluded.geography,");
    lines.push("  reference_area = excluded.reference_area,");
    lines.push("  year = excluded.year,");
    lines.push("  adi = excluded.adi,");
    lines.push("  financial_strength = excluded.financial_strength,");
    lines.push("  economic_hardship_and_inequality = excluded.economic_hardship_and_inequality,");
    lines.push("  educational_attainment = excluded.educational_attainment,");
    lines.push("  source = excluded.source,");
    lines.push("  updated_at = now();");
  }

  if (failures.length > 0) {
    lines.push("");
    lines.push("-- Failed ZIPs:");
    for (const failure of failures) {
      lines.push(`-- ${failure.zip}: ${failure.error.replaceAll("\n", " ")}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function sqlTuple(row) {
  return [
    `  (${sqlString(row.zip)}`,
    sqlString(row.geography),
    sqlString(row.referenceArea || ""),
    sqlNumber(row.year),
    sqlNumber(row.adi),
    sqlNumber(row.financialStrength),
    sqlNumber(row.economicHardshipAndInequality),
    sqlNumber(row.educationalAttainment),
    `${sqlString(row.source || "sociome acs5")})`
  ].join(", ");
}

function sqlString(value) {
  return `'${String(value || "").replaceAll("'", "''")}'`;
}

function sqlNumber(value) {
  if (value == null || value === "") return "null";
  return Number.isFinite(Number(value)) ? String(Number(value)) : "null";
}
